postgresql:
  auth:
    username: postgres
    password: postgres
    database: votingdb

redis:
  image: redis
  replicaCount: 1

votingApp:
  image: kodekloud/examplevotingapp_vote:v1
  service:
    type: NodePort
    nodePort: 30004

resultApp:
  image: kodekloud/examplevotingapp_result:v1
  service:
    type: NodePort
    nodePort: 30005

workerApp:
  image: kodekloud/examplevotingapp_worker:v1
